# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebStreamer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebStreamer
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'IQKeyboardManager'
  pod 'GTProgressBar'
  pod 'AFNetworking', :git => 'https://github.com/xinhua01206/AFNetworking'
  pod 'SwiftyGif'
  pod 'SVProgressHUD'
  pod 'Logboard'
  pod 'SVGKit'
  pod 'SDWebImage'

  target 'WebStreamerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebStreamerUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
